server:
  port: 8089
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/product_map?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.huawei.vo
logging:
    level:
       com.huawei.dao : debug
swagger:
   enabled : true
   title : 地图接口
   description :  地图接口说明
   license : Apache License, Version 2.0
   licenseUrl : https://www.apache.org/licenses/LICENSE-2.0.html
   termsOfServiceUrl : https://github.com/dyc87112/spring-boot-starter-swagger
   base-package : com.huawei.controller
   base-path : /**
   exclude-path : /error, /ops/**
   contact :
      name : 胥伟
      url : https://www.jianshu.com/u/822585e5c69a
      email : 1101516243@qq.com