package com.huawei.vo;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.productName
     *
     * @mbggenerated
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.productDesc1
     *
     * @mbggenerated
     */
    private String productdesc1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.productDesc2
     *
     * @mbggenerated
     */
    private String productdesc2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.weight
     *
     * @mbggenerated
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.productOrigin
     *
     * @mbggenerated
     */
    private String productorigin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.productBz
     *
     * @mbggenerated
     */
    private String productbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.productShape
     *
     * @mbggenerated
     */
    private String productshape;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.price
     *
     * @mbggenerated
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.producttypeid
     *
     * @mbggenerated
     */
    private String producttypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.brandId
     *
     * @mbggenerated
     */
    private String brandid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.ID
     *
     * @return the value of tb_product.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.ID
     *
     * @param id the value for tb_product.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.productName
     *
     * @return the value of tb_product.productName
     *
     * @mbggenerated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.productName
     *
     * @param productname the value for tb_product.productName
     *
     * @mbggenerated
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.productDesc1
     *
     * @return the value of tb_product.productDesc1
     *
     * @mbggenerated
     */
    public String getProductdesc1() {
        return productdesc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.productDesc1
     *
     * @param productdesc1 the value for tb_product.productDesc1
     *
     * @mbggenerated
     */
    public void setProductdesc1(String productdesc1) {
        this.productdesc1 = productdesc1 == null ? null : productdesc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.productDesc2
     *
     * @return the value of tb_product.productDesc2
     *
     * @mbggenerated
     */
    public String getProductdesc2() {
        return productdesc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.productDesc2
     *
     * @param productdesc2 the value for tb_product.productDesc2
     *
     * @mbggenerated
     */
    public void setProductdesc2(String productdesc2) {
        this.productdesc2 = productdesc2 == null ? null : productdesc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.weight
     *
     * @return the value of tb_product.weight
     *
     * @mbggenerated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.weight
     *
     * @param weight the value for tb_product.weight
     *
     * @mbggenerated
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.productOrigin
     *
     * @return the value of tb_product.productOrigin
     *
     * @mbggenerated
     */
    public String getProductorigin() {
        return productorigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.productOrigin
     *
     * @param productorigin the value for tb_product.productOrigin
     *
     * @mbggenerated
     */
    public void setProductorigin(String productorigin) {
        this.productorigin = productorigin == null ? null : productorigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.productBz
     *
     * @return the value of tb_product.productBz
     *
     * @mbggenerated
     */
    public String getProductbz() {
        return productbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.productBz
     *
     * @param productbz the value for tb_product.productBz
     *
     * @mbggenerated
     */
    public void setProductbz(String productbz) {
        this.productbz = productbz == null ? null : productbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.productShape
     *
     * @return the value of tb_product.productShape
     *
     * @mbggenerated
     */
    public String getProductshape() {
        return productshape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.productShape
     *
     * @param productshape the value for tb_product.productShape
     *
     * @mbggenerated
     */
    public void setProductshape(String productshape) {
        this.productshape = productshape == null ? null : productshape.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.price
     *
     * @return the value of tb_product.price
     *
     * @mbggenerated
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.price
     *
     * @param price the value for tb_product.price
     *
     * @mbggenerated
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.producttypeid
     *
     * @return the value of tb_product.producttypeid
     *
     * @mbggenerated
     */
    public String getProducttypeid() {
        return producttypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.producttypeid
     *
     * @param producttypeid the value for tb_product.producttypeid
     *
     * @mbggenerated
     */
    public void setProducttypeid(String producttypeid) {
        this.producttypeid = producttypeid == null ? null : producttypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.brandId
     *
     * @return the value of tb_product.brandId
     *
     * @mbggenerated
     */
    public String getBrandid() {
        return brandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.brandId
     *
     * @param brandid the value for tb_product.brandId
     *
     * @mbggenerated
     */
    public void setBrandid(String brandid) {
        this.brandid = brandid == null ? null : brandid.trim();
    }
}